### ISSUE TITLE
Netlify documentation broken

### ISSUE THREAD

**Issue by raimund-schluessler** [nextcloud/nextcloud-vue#1284]
No idea why, but the documentation https://nextcloud-vue-components.netlify.app/ only shows this:

![Screenshot_2020-08-13 Page Not Found](https://user-images.githubusercontent.com/2496460/90169509-f5679900-dd9e-11ea-9569-ebe7da006283.png)

@nextcloud/vuejs Does anyone have an idea or can debug this?

**Comment by raimund-schluessler** [comment]
Might be that #1281 broke it, but I don't know why though.

**Comment by skjnldsv** [comment]
Redeployed https://app.netlify.com/sites/nextcloud-vue-components/deploys/5f35810b3c79c7a2ee144f7a

**Comment by skjnldsv** [comment]
```
8:08:02 PM: (node:1667) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected character '#' (2:0)
8:08:02 PM:     at Object.pp$4.raise (/opt/build/repo/node_modules/vue-inbrowser-compiler/node_modules/acorn/dist/acorn.js:2825:15)
8:08:02 PM:     at Object.pp$9.getTokenFromCode (/opt/build/repo/node_modules/vue-inbrowser-compiler/node_modules/acorn/dist/acorn.js:4560:10)
8:08:02 PM:     at Object.pp$9.readToken (/opt/build/repo/node_modules/vue-inbrowser-compiler/node_modules/acorn/dist/acorn.js:4288:17)
8:08:02 PM:     at Object.readToken (/opt/build/repo/node_modules/acorn-jsx/index.js:469:20)
8:08:02 PM:     at Object.pp$9.nextToken (/opt/build/repo/node_modules/vue-inbrowser-compiler/node_modules/acorn/dist/acorn.js:4279:17)
8:08:02 PM:     at Object.parse (/opt/build/repo/node_modules/vue-inbrowser-compiler/node_modules/acorn/dist/acorn.js:552:10)
8:08:02 PM:     at Function.parse (/opt/build/repo/node_modules/vue-inbrowser-compiler/node_modules/acorn/dist/acorn.js:576:37)
8:08:02 PM:     at getAst (/opt/build/repo/node_modules/vue-inbrowser-compiler/lib/vue-inbrowser-compiler.cjs.js:86:31)
8:08:02 PM:     at prepareVueCodeForEvalFunction (/opt/build/repo/node_modules/vue-inbrowser-compiler/lib/vue-inbrowser-compiler.cjs.js:252:19)
8:08:02 PM:     at compileVueCodeForEvalFunction (/opt/build/repo/node_modules/vue-inbrowser-compiler/lib/vue-inbrowser-compiler.cjs.js:222:36)
8:08:02 PM:     at /opt/build/repo/node_modules/vue-styleguidist/lib/loaders/examples-loader.js:237:77
8:08:02 PM:     at Array.map (<anonymous>)
8:08:02 PM:     at Object._callee$ (/opt/build/repo/node_modules/vue-styleguidist/lib/loaders/examples-loader.js:222:41)
8:08:02 PM:     at tryCatch (/opt/build/repo/node_modules/regenerator-runtime/runtime.js:63:40)
8:08:02 PM:     at Generator.invoke [as _invoke] (/opt/build/repo/node_modules/regenerator-runtime/runtime.js:293:22)
8:08:02 PM:     at Generator.next (/opt/build/repo/node_modules/regenerator-runtime/runtime.js:118:21)
8:08:02 PM:     at asyncGeneratorStep (/opt/build/repo/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
8:08:02 PM:     at _next (/opt/build/repo/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
8:08:02 PM:     at /opt/build/repo/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
8:08:02 PM:     at new Promise (<anonymous>)
8:08:02 PM:     at Object.<anonymous> (/opt/build/repo/node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12)
8:08:02 PM:     at Object.examplesLoader (/opt/build/repo/node_modules/vue-styleguidist/lib/loaders/examples-loader.js:89:26)
8:08:02 PM: (node:1667) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
8:08:02 PM: (node:1667) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by raimund-schluessler** [comment]
@skjnldsv Do you have an idea where this error comes from? It doesn't name any file.

**Comment by raimund-schluessler** [comment]
Ah, I think I know. Let me fix.

**Comment by skjnldsv** [comment]
No idea. But npm run styleguide works 🤷

**Comment by raimund-schluessler** [comment]
#1285 fixes the issue. I overlooked a " ``` " in the docs section, that's probably why the linters didn't find it.
