### ISSUE TITLE
build issue with version 4

### ISSUE THREAD

**Issue by StCyr** [nextcloud/nextcloud-vue#2184]
My CI makes an error when running my npm test when I depend on @Nextcloud/vue version 4.x.

The error goes away when I switch to @Nextcloud/vue version 3.10.1 (which doesn't use splitpanes)

```
Run npm test

> workspace@1.0.0 test /home/runner/work/workspace/workspace
> NODE_ENV=testing mochapack --webpack-config webpack.test.config.js --require "src/tests/OC.js" "src/tests/**/*.js"

Building workspace 1.0.0 

 WEBPACK  Compiling...

Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools
You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
 WEBPACK  Compiled successfully in 4283ms

 MOCHA  Testing...

 RUNTIME EXCEPTION  Exception occurred while loading your tests

/home/runner/work/workspace/workspace/node_modules/splitpanes/dist/splitpanes.css:1
.splitpanes{display:-webkit-box;display:-ms-flexbox;display:flex;width:100%;height:100%}.splitpanes--vertical{-webkit-box-orient:horizontal;-webkit-box-direction:normal;-ms-flex-direction:row;flex-direction:row}.splitpanes--horizontal{-webkit-box-orient:vertical;-webkit-box-direction:normal;-ms-flex-direction:column;flex-direction:column}.splitpanes--dragging *{-webkit-user-select:none;-moz-user-select:none;-ms-user-select:none;user-select:none}.splitpanes__pane{width:100%;height:100%;overflow:hidden}.splitpanes--vertical .splitpanes__pane{-webkit-transition:width .2s ease-out;transition:width .2s ease-out}.splitpanes--horizontal .splitpanes__pane{-webkit-transition:height .2s ease-out;transition:height .2s ease-out}.splitpanes--dragging .splitpanes__pane{-webkit-transition:none;transition:none}.splitpanes__splitter{-ms-touch-action:none;touch-action:none}.splitpanes--vertical>.splitpanes__splitter{min-width:1px;cursor:col-r

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.module_1.default._extensions.(anonymous function) [as .js] (/home/runner/work/workspace/workspace/node_modules/mochapack/src/util/registerRequireHook.ts:99:53)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.call (/home/runner/work/workspace/workspace/node_modules/@nextcloud/vue/dist/Components/webpack:/NextcloudVue.[name]/external "splitpanes/dist/splitpanes.css":1:18)
    at __webpack_require__ (/home/runner/work/workspace/workspace/node_modules/@nextcloud/vue/dist/Components/webpack:/NextcloudVue.[name]/webpack/bootstrap:19:22)
    at Object.call (/home/runner/work/workspace/workspace/node_modules/@nextcloud/vue/dist/Components/webpack:/NextcloudVue.[name]/src/components/AppContent/AppContent.vue:111:1)
    at __webpack_require__ (/home/runner/work/workspace/workspace/node_modules/@nextcloud/vue/dist/Components/webpack:/NextcloudVue.[name]/webpack/bootstrap:19:22)
    at Module.call (/home/runner/work/workspace/workspace/node_modules/@nextcloud/vue/dist/Components/webpack:/NextcloudVue.[name]/src/components/AppContent/AppContent.vue?2bc6:1:1)
    at __webpack_require__ (/home/runner/work/workspace/workspace/node_modules/@nextcloud/vue/dist/Components/webpack:/NextcloudVue.[name]/webpack/bootstrap:19:22)
    at Module.call (/home/runner/work/workspace/workspace/node_modules/@nextcloud/vue/dist/Components/webpack:/NextcloudVue.[name]/src/components/AppContent/AppContent.vue:1:1)
    at n (/home/runner/work/workspace/workspace/node_modules/@nextcloud/vue/dist/Components/webpack:/NextcloudVue.[name]/webpack/bootstrap:19:22)

npm ERR! Test failed.  See above for more details.
Error: Process completed with exit code 1.
```

**Comment by raimund-schluessler** [comment]
I guess there is an issue with your webpack config. The recommended solution is anyway to use the shared webpack config provided here: https://github.com/nextcloud/webpack-vue-config

**Comment by dartcafe** [comment]
Waaa. I don't know, where I got this trace from. ;-) 

This is the right one from the failed CI: 
```
ERROR in ./node_modules/linkify-string/index.js 1:0-56
Module not found: Error: Can't resolve 'linkifyjs/lib/linkify-string' in '/home/runner/work/polls/polls/node_modules/linkify-string'
resolve 'linkifyjs/lib/linkify-string' in '/home/runner/work/polls/polls/node_modules/linkify-string'
  Parsed request is a module
  using description file: /home/runner/work/polls/polls/node_modules/linkify-string/package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /home/runner/work/polls/polls/node_modules/linkify-string/node_modules doesn't exist or is not a directory
      /home/runner/work/polls/polls/node_modules/node_modules doesn't exist or is not a directory
      looking for modules in /home/runner/work/polls/polls/node_modules
        /home/runner/work/polls/polls/node_modules/linkifyjs doesn't exist
      /home/runner/work/polls/node_modules doesn't exist or is not a directory
      /home/runner/work/node_modules doesn't exist or is not a directory
      /home/runner/node_modules doesn't exist or is not a directory
      /home/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
 @ ./node_modules/@nextcloud/vue/dist/ncvuecomponents.js 150:408-433
 @ ./src/js/main.js 34:0-41 53:25-32

```

**Comment by raimund-schluessler** [comment]
Closing since no response and not reproducible.
