### ISSUE TITLE
Problem to run tests with the version 4.3.0

### ISSUE THREAD

**Issue by zak39** [nextcloud/nextcloud-vue#2478]
Hi :slightly_smiling_face: 

I have a problem to run my tests with the version 4.3.0 of `@nextcloud/vue` and generate this error : 

```
$ npm test

> workspace@1.0.0 test
> mochapack --webpack-config webpack.test.config.js --require "src/tests/OC.js" "src/tests/**/*.js"

Building workspace 1.0.0 

  [=                        ] 3% (setup) WEBPACK  Compiling...

  [===                      ] 10% (building)Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools
You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
  [=========================] 98% (emitting) WEBPACK  Compiled successfully in 19538ms

 MOCHA  Testing...

 RUNTIME EXCEPTION  Exception occurred while loading your tests

/home/zak/Documents/arawa/codes/workspace/node_modules/splitpanes/dist/splitpanes.css:1
.splitpanes{display:-webkit-box;display:-ms-flexbox;display:flex;width:100%;height:100%}.splitpanes--vertical{-webkit-box-orient:horizontal;-webkit-box-direction:normal;-ms-flex-direction:row;flex-direction:row}.splitpanes--horizontal{-webkit-box-orient:vertical;-webkit-box-direction:normal;-ms-flex-direction:column;flex-direction:column}.splitpanes--dragging *{-webkit-user-select:none;-moz-user-select:none;-ms-user-select:none;user-select:none}.splitpanes__pane{width:100%;height:100%;overflow:hidden}.splitpanes--vertical .splitpanes__pane{-webkit-transition:width .2s ease-out;transition:width .2s ease-out}.splitpanes--horizontal .splitpanes__pane{-webkit-transition:height .2s ease-out;transition:height .2s ease-out}.splitpanes--dragging .splitpanes__pane{-webkit-transition:none;transition:none}.splitpanes__splitter{-ms-touch-action:none;touch-action:none}.splitpanes--vertical>.splitpanes__splitter{min-width:1px;cursor:col-resize}.splitpanes--horizontal>.splitpanes__splitter{min-height:1px;cursor:row-resize}.splitpanes.default-theme .splitpanes__pane{background-color:#f2f2f2}.splitpanes.default-theme .splitpanes__splitter{background-color:#fff;-webkit-box-sizing:border-box;box-sizing:border-box;position:relative;-ms-flex-negative:0;flex-shrink:0}.splitpanes.default-theme .splitpanes__splitter:after,.splitpanes.default-theme .splitpanes__splitter:before{content:"";position:absolute;top:50%;left:50%;background-color:rgba(0,0,0,.15);-webkit-transition:background-color .3s;transition:background-color .3s}.splitpanes.default-theme .splitpanes__splitter:hover:after,.splitpanes.default-theme .splitpanes__splitter:hover:before{background-color:rgba(0,0,0,.25)}.splitpanes.default-theme .splitpanes__splitter:first-child{cursor:auto}.default-theme.splitpanes .splitpanes .splitpanes__splitter{z-index:1}.default-theme.splitpanes--vertical>.splitpanes__splitter,.default-theme .splitpanes--vertical>.splitpanes__splitter{width:7px;border-left:1px solid #eee;margin-left:-1px}.default-theme.splitpanes--vertical>.splitpanes__splitter:after,.default-theme .splitpanes--vertical>.splitpanes__splitter:after,.default-theme.splitpanes--vertical>.splitpanes__splitter:before,.default-theme .splitpanes--vertical>.splitpanes__splitter:before{-webkit-transform:translateY(-50%);transform:translateY(-50%);width:1px;height:30px}.default-theme.splitpanes--vertical>.splitpanes__splitter:before,.default-theme .splitpanes--vertical>.splitpanes__splitter:before{margin-left:-2px}.default-theme.splitpanes--vertical>.splitpanes__splitter:after,.default-theme .splitpanes--vertical>.splitpanes__splitter:after{margin-left:1px}.default-theme.splitpanes--horizontal>.splitpanes__splitter,.default-theme .splitpanes--horizontal>.splitpanes__splitter{height:7px;border-top:1px solid #eee;margin-top:-1px}.default-theme.splitpanes--horizontal>.splitpanes__splitter:after,.default-theme .splitpanes--horizontal>.splitpanes__splitter:after,.default-theme.splitpanes--horizontal>.splitpanes__splitter:before,.default-theme .splitpanes--horizontal>.splitpanes__splitter:before{-webkit-transform:translateX(-50%);transform:translateX(-50%);width:30px;height:1px}.default-theme.splitpanes--horizontal>.splitpanes__splitter:before,.default-theme .splitpanes--horizontal>.splitpanes__splitter:before{margin-top:-2px}.default-theme.splitpanes--horizontal>.splitpanes__splitter:after,.default-theme .splitpanes--horizontal>.splitpanes__splitter:after{margin-top:1px}
^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.module_1.default._extensions.<computed> [as .js] (/home/zak/Documents/arawa/codes/workspace/node_modules/mochapack/src/util/registerRequireHook.ts:99:53)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.call (/home/zak/Documents/arawa/codes/workspace/node_modules/@nextcloud/vue/dist/Components/webpack:/NextcloudVue.[name]/external "splitpanes/dist/splitpanes.css":1:18)
    at n (/home/zak/Documents/arawa/codes/workspace/node_modules/@nextcloud/vue/dist/Components/webpack:/NextcloudVue.[name]/webpack/bootstrap:19:22)
    at Module.call (/home/zak/Documents/arawa/codes/workspace/node_modules/@nextcloud/vue/dist/Components/AppContent.js:1:15021)
    at __webpack_require__ (/home/zak/Documents/arawa/codes/workspace/node_modules/@nextcloud/vue/dist/Components/webpack:/NextcloudVue.[name]/webpack/bootstrap:19:22)
    at 0 (/home/zak/Documents/arawa/codes/workspace/node_modules/@nextcloud/vue/dist/Components/webpack:/NextcloudVue.[name]/webpack/bootstrap:83:10)
    at factory (/home/zak/Documents/arawa/codes/workspace/node_modules/@nextcloud/vue/dist/Components/AppContent.js:1:1253)
    at /home/zak/Documents/arawa/codes/workspace/node_modules/@nextcloud/vue/dist/Components/webpack:/NextcloudVue.[name]/webpack/universalModuleDefinition:3:20
    at Object.<anonymous> (/home/zak/Documents/arawa/codes/workspace/node_modules/@nextcloud/vue/dist/Components/webpack:/NextcloudVue.[name]/webpack/universalModuleDefinition:1:1)

  [=========================] 100% (completed)
```

When I downgrade the `@nextcloud/vue` package to `^3.10.1`, I didn't have this error message :

```
$ npm test

> workspace@1.0.0 test
> mochapack --webpack-config webpack.test.config.js --require "src/tests/OC.js" "src/tests/**/*.js"

Building workspace 1.0.0 

  [                         ] 0% () WEBPACK  Compiling...

  [===                      ] 10% (building)Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools
You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
  [=========================] 98% (emitting) WEBPACK  Compiled successfully in 18437ms

 MOCHA  Testing...

[vue-router] Named Route 'home' has a default child route. When navigating to this named route (:to="{name: 'home'"), the default child route will not be rendered. Remove the name from this route and use the name of the default child route for named links instead.
[Vue warn]: Unknown custom element: <notifications> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <Home> at src/Home.vue
       <Root>
  [=========================] 100% (completed)



  Home component tests
    ✔ ConvertQuotaForFrontend: Test regular quota
    ✔ ConvertQuotaForFrontend: Test unlimited quota

  SelectUsers component tests
    ✔ addUsersToWorkspaceOrGroup test: Adding a user to a subgroup
Problem to load spaces only Error: Request failed with status code 404
    at createError (/home/zak/Documents/arawa/codes/workspace/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/zak/Documents/arawa/codes/workspace/node_modules/axios/lib/core/settle.js:17:12)
    at XMLHttpRequest.onloadend (/home/zak/Documents/arawa/codes/workspace/node_modules/axios/lib/adapters/xhr.js:66:7)
    at XMLHttpRequest.invokeTheCallbackFunction (/home/zak/Documents/arawa/codes/workspace/node_modules/jsdom/lib/jsdom/living/generated/EventHandlerNonNull.js:14:28)
    at XMLHttpRequest.<anonymous> (/home/zak/Documents/arawa/codes/workspace/node_modules/jsdom/lib/jsdom/living/helpers/create-event-accessor.js:35:32)
    at innerInvokeEventListeners (/home/zak/Documents/arawa/codes/workspace/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:340:25)
    at invokeEventListeners (/home/zak/Documents/arawa/codes/workspace/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:276:3)
    at XMLHttpRequestImpl._dispatch (/home/zak/Documents/arawa/codes/workspace/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:223:9)
    at fireAnEvent (/home/zak/Documents/arawa/codes/workspace/node_modules/jsdom/lib/jsdom/living/helpers/events.js:18:36)
    at Request.<anonymous> (/home/zak/Documents/arawa/codes/workspace/node_modules/jsdom/lib/jsdom/living/xhr/XMLHttpRequest-impl.js:891:5)
    at Request.emit (events.js:412:35)
    at IncomingMessage.<anonymous> (/home/zak/Documents/arawa/codes/workspace/node_modules/jsdom/lib/jsdom/living/helpers/http-request.js:230:42)
    at Object.onceWrapper (events.js:519:28)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1334:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: xhrAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    headers: { Accept: 'application/json, text/plain, */*', requesttoken: '' },
    method: 'get',
    url: 'undefined/apps/workspace/spaces',
    data: undefined
  },
  request: XMLHttpRequest {},
  response: {
    data: '<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n' +
      '<html><head>\n' +
      '<title>404 Not Found</title>\n' +
      '</head><body>\n' +
      '<h1>Not Found</h1>\n' +
      '<p>The requested URL was not found on this server.</p>\n' +
      '<hr>\n' +
      '<address>Apache/2.4.41 (Ubuntu) Server at localhost Port 80</address>\n' +
      '</body></html>\n',
    status: 404,
    statusText: 'Not Found',
    headers: {
      date: 'Mon, 07 Feb 2022 15:01:51 GMT',
      server: 'Apache/2.4.41 (Ubuntu)',
      'access-control-allow-origin': '*',
      'content-length': '271',
      'keep-alive': 'timeout=5, max=100',
      connection: 'Keep-Alive',
      'content-type': 'text/html; charset=iso-8859-1'
    },
    config: {
      transitional: [Object],
      adapter: [Function: xhrAdapter],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      validateStatus: [Function: validateStatus],
      headers: [Object],
      method: 'get',
      url: 'undefined/apps/workspace/spaces',
      data: undefined
    },
    request: XMLHttpRequest {}
  },
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
    ✔ addUsersToWorkspaceOrGroup test: Adding a user to a workspace
The error is : Error: Request failed with status code 405
e.message Request failed with status code 405
e.name Error
e.lineNumber undefined
e.columnNumber undefined
e.stack Error: Request failed with status code 405
    at createError (/home/zak/Documents/arawa/codes/workspace/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/zak/Documents/arawa/codes/workspace/node_modules/axios/lib/core/settle.js:17:12)
    at XMLHttpRequest.onloadend (/home/zak/Documents/arawa/codes/workspace/node_modules/axios/lib/adapters/xhr.js:66:7)
    at XMLHttpRequest.invokeTheCallbackFunction (/home/zak/Documents/arawa/codes/workspace/node_modules/jsdom/lib/jsdom/living/generated/EventHandlerNonNull.js:14:28)
    at XMLHttpRequest.<anonymous> (/home/zak/Documents/arawa/codes/workspace/node_modules/jsdom/lib/jsdom/living/helpers/create-event-accessor.js:35:32)
    at innerInvokeEventListeners (/home/zak/Documents/arawa/codes/workspace/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:340:25)
    at invokeEventListeners (/home/zak/Documents/arawa/codes/workspace/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:276:3)
    at XMLHttpRequestImpl._dispatch (/home/zak/Documents/arawa/codes/workspace/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:223:9)
    at fireAnEvent (/home/zak/Documents/arawa/codes/workspace/node_modules/jsdom/lib/jsdom/living/helpers/events.js:18:36)
    at Request.<anonymous> (/home/zak/Documents/arawa/codes/workspace/node_modules/jsdom/lib/jsdom/living/xhr/XMLHttpRequest-impl.js:891:5)
    at Request.emit (events.js:412:35)
    at IncomingMessage.<anonymous> (/home/zak/Documents/arawa/codes/workspace/node_modules/jsdom/lib/jsdom/living/helpers/http-request.js:230:42)
    at Object.onceWrapper (events.js:519:28)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1334:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
The error is : Error: Request failed with status code 405
e.message Request failed with status code 405
e.name Error
e.lineNumber undefined
e.columnNumber undefined
e.stack Error: Request failed with status code 405
    at createError (/home/zak/Documents/arawa/codes/workspace/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/zak/Documents/arawa/codes/workspace/node_modules/axios/lib/core/settle.js:17:12)
    at XMLHttpRequest.onloadend (/home/zak/Documents/arawa/codes/workspace/node_modules/axios/lib/adapters/xhr.js:66:7)
    at XMLHttpRequest.invokeTheCallbackFunction (/home/zak/Documents/arawa/codes/workspace/node_modules/jsdom/lib/jsdom/living/generated/EventHandlerNonNull.js:14:28)
    at XMLHttpRequest.<anonymous> (/home/zak/Documents/arawa/codes/workspace/node_modules/jsdom/lib/jsdom/living/helpers/create-event-accessor.js:35:32)
    at innerInvokeEventListeners (/home/zak/Documents/arawa/codes/workspace/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:340:25)
    at invokeEventListeners (/home/zak/Documents/arawa/codes/workspace/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:276:3)
    at XMLHttpRequestImpl._dispatch (/home/zak/Documents/arawa/codes/workspace/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:223:9)
    at fireAnEvent (/home/zak/Documents/arawa/codes/workspace/node_modules/jsdom/lib/jsdom/living/helpers/events.js:18:36)
    at Request.<anonymous> (/home/zak/Documents/arawa/codes/workspace/node_modules/jsdom/lib/jsdom/living/xhr/XMLHttpRequest-impl.js:891:5)
    at Request.emit (events.js:412:35)
    at IncomingMessage.<anonymous> (/home/zak/Documents/arawa/codes/workspace/node_modules/jsdom/lib/jsdom/living/helpers/http-request.js:230:42)
    at Object.onceWrapper (events.js:519:28)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1334:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
    ✔ addUsersToWorkspaceOrGroup test: Adding a user to a workspace with admin role
The error is : Error: Request failed with status code 405
e.message Request failed with status code 405
e.name Error
e.lineNumber undefined
e.columnNumber undefined
e.stack Error: Request failed with status code 405
    at createError (/home/zak/Documents/arawa/codes/workspace/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/zak/Documents/arawa/codes/workspace/node_modules/axios/lib/core/settle.js:17:12)
    at XMLHttpRequest.onloadend (/home/zak/Documents/arawa/codes/workspace/node_modules/axios/lib/adapters/xhr.js:66:7)
    at XMLHttpRequest.invokeTheCallbackFunction (/home/zak/Documents/arawa/codes/workspace/node_modules/jsdom/lib/jsdom/living/generated/EventHandlerNonNull.js:14:28)
    at XMLHttpRequest.<anonymous> (/home/zak/Documents/arawa/codes/workspace/node_modules/jsdom/lib/jsdom/living/helpers/create-event-accessor.js:35:32)
    at innerInvokeEventListeners (/home/zak/Documents/arawa/codes/workspace/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:340:25)
    at invokeEventListeners (/home/zak/Documents/arawa/codes/workspace/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:276:3)
    at XMLHttpRequestImpl._dispatch (/home/zak/Documents/arawa/codes/workspace/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:223:9)
    at fireAnEvent (/home/zak/Documents/arawa/codes/workspace/node_modules/jsdom/lib/jsdom/living/helpers/events.js:18:36)
    at Request.<anonymous> (/home/zak/Documents/arawa/codes/workspace/node_modules/jsdom/lib/jsdom/living/xhr/XMLHttpRequest-impl.js:891:5)
    at Request.emit (events.js:412:35)
    at IncomingMessage.<anonymous> (/home/zak/Documents/arawa/codes/workspace/node_modules/jsdom/lib/jsdom/living/helpers/http-request.js:230:42)
    at Object.onceWrapper (events.js:519:28)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1334:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)

  Vuex store tests
    ✔ Adds a space in the Vuex store
The error is : Error: Request failed with status code 405
e.message Request failed with status code 405
e.name Error
e.lineNumber undefined
e.columnNumber undefined
e.stack Error: Request failed with status code 405
    at createError (/home/zak/Documents/arawa/codes/workspace/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/zak/Documents/arawa/codes/workspace/node_modules/axios/lib/core/settle.js:17:12)
    at XMLHttpRequest.onloadend (/home/zak/Documents/arawa/codes/workspace/node_modules/axios/lib/adapters/xhr.js:66:7)
    at XMLHttpRequest.invokeTheCallbackFunction (/home/zak/Documents/arawa/codes/workspace/node_modules/jsdom/lib/jsdom/living/generated/EventHandlerNonNull.js:14:28)
    at XMLHttpRequest.<anonymous> (/home/zak/Documents/arawa/codes/workspace/node_modules/jsdom/lib/jsdom/living/helpers/create-event-accessor.js:35:32)
    at innerInvokeEventListeners (/home/zak/Documents/arawa/codes/workspace/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:340:25)
    at invokeEventListeners (/home/zak/Documents/arawa/codes/workspace/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:276:3)
    at XMLHttpRequestImpl._dispatch (/home/zak/Documents/arawa/codes/workspace/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:223:9)
    at fireAnEvent (/home/zak/Documents/arawa/codes/workspace/node_modules/jsdom/lib/jsdom/living/helpers/events.js:18:36)
    at Request.<anonymous> (/home/zak/Documents/arawa/codes/workspace/node_modules/jsdom/lib/jsdom/living/xhr/XMLHttpRequest-impl.js:891:5)
    at Request.emit (events.js:412:35)
    at IncomingMessage.<anonymous> (/home/zak/Documents/arawa/codes/workspace/node_modules/jsdom/lib/jsdom/living/helpers/http-request.js:230:42)
    at Object.onceWrapper (events.js:519:28)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1334:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
    ✔ Adds a group to the space
    ✔ Removes a group to the space
    ✔ Sets space quota
    ✔ Get space quota
    ✔ Adds a user to the space
    ✔ Count users in workspace
    ✔ Count users in group
    ✔ Removes a user from the space


  14 passing (215ms)

 MOCHA  Tests completed successfully
```

I don't understand why I have a problem with the version `4.3.0` of the `@nextcloud/vue` package.

I think the problem comes of the `splitpanes` package ? :thinking: 

I don't know if someone has this problem ?

Here is the repository of my project : https://github.com/arawa/workspace

And the PR I am working : https://github.com/arawa/workspace/pull/413

I found this request from @StCyr from 5 months ago : https://gitmemory.cn/index.php/repo/nextcloud/nextcloud-vue/issues/2184

Here is my `package.json` :

```json
{
  "name": "workspace",
  "version": "1.0.0",
  "description": "Place this app in **nextcloud/apps/**",
  "main": "main.js",
  "private": true,
  "scripts": {
    "build": "webpack --node-env production --progress",
		"dev": "webpack --node-env development --progress",
		"watch": "webpack --node-env development --progress --watch",
		"serve": "webpack --node-env development serve --progress",
    "test": "mochapack --webpack-config webpack.test.config.js --require \"src/tests/OC.js\" \"src/tests/**/*.js\"",
    "lint": "eslint --ext .js,.vue src"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/arawa/workspace.git"
  },
  "keywords": [],
  "author": "Arawa <https://www.arawa.fr/>",
  "contributors": [
    {
      "name": "Baptiste Fotia",
      "email": "baptiste.fotia@arawa.fr"
    },
    {
      "name": "Cyrille Bollu",
      "email": "cyrille@bollu.be"
    }
  ],
  "license": "AGPL-3.0-or-later",
  "bugs": {
    "url": "https://github.com/arawa/workspace/issues"
  },
  "homepage": "https://github.com/arawa/workspace#readme",
  "engines": {
    "npm": "^7.0.0",
    "node": "^14.0.0"
  },
  "devDependencies": {
    "@nextcloud/babel-config": "^1.0.0",
    "@nextcloud/browserslist-config": "^2.2.0",
    "@nextcloud/eslint-config": "^6.1.2",
    "@nextcloud/stylelint-config": "^2.1.2",
    "@nextcloud/webpack-vue-config": "^4.3.2",
    "@vue/test-utils": "^1.3.0",
    "chai": "^4.3.6",
    "jsdom": "^19.0.0",
    "jsdom-global": "^3.0.2",
    "mochapack": "^2.1.4",
    "prettier": "^2.5.1",
    "webpack-node-externals": "^3.0.0"
  },
  "dependencies": {
    "@nextcloud/axios": "^1.9.0",
    "@nextcloud/l10n": "^1.4.1",
    "@nextcloud/router": "^1.2.0",
    "@nextcloud/vue": "^4.3.0",
    "ramda": "^0.28.0",
    "vue": "^2.6.12",
    "vue-notification": "^1.3.20",
    "vue-router": "^3.5.3",
    "vuex": "^3.6.2"
  },
  "optionalDependencies": {
    "fsevents": "^2.3.2"
  }
}
```

And my `webpack.config.js` file :

```javascript
/**
 * @copyright Copyright (c) 2017 Arawa
 *
 * @author 2021 Baptiste Fotia <baptiste.fotia@arawa.fr>
 * @author 2021 Cyrille Bollu <cyrille@bollu.be>
 *
 * @license GNU AGPL version 3 or any later version
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

const webpackConfig = require('@nextcloud/webpack-vue-config')

module.exports = webpackConfig
```

**Comment by raimund-schluessler** [comment]
Is this still an issue?

**Comment by raimund-schluessler** [comment]
Closing as no response and cannot reproduce.
